spring.application.name=vlc
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SQL_URL}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASS}

#Para testing sin docker...
#spring.datasource.username=root
#spring.datasource.password=toor
#spring.datasource.url=jdbc:mysql://localhost:3306/todo_vlc


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Seguridad contra Cross site Scripting, XSS (JavaScript), por si acaso
server.servlet.session.cookie.http-only=true

#Por defecto las sesiones de usuario duran 14 dias.